### ISSUE TITLE
Some builds didn't complete successfully and had errors:

### ISSUE THREAD

**Issue by david-freistrom** [francisck/DanderSpritz_lab#1]
Hi,

packer build runs into error. 

--> Domain_Controller: Error uploading guest additions: Error uploading file to $env:TEMP\winrmcp-5b39b198-4c37-1d4f-77e8-53e67f0f8680.tmp: Couldn't create shell: http error: 500 - <s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.dmtf.org/wbem/wsman/1/wsman/fault</a:Action><a:MessageID>uuid:9AF3622B-D04E-4337-A1BF-2169190BC534</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:cd847835-caab-4369-47b5-f479e996335b</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Receiver</s:Value><s:Subcode><s:Value>w:InternalError</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">Server execution failed </s:Text></s:Reason><s:Detail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2148007941" Machine="127.0.0.1"><f:Message><f:ProviderFault provider="Shell cmd plugin" path="%systemroot%\system32\winrscmd.dll">Server execution failed </f:ProviderFault></f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>
--> Target: Error uploading guest additions: Error restoring file from $env:TEMP\winrmcp-5b39b1ab-9751-3230-44cb-07a6d8e7c800.tmp to VBoxGuestAdditions.iso: restore operation returned code=1

==> Builds finished. The artifacts of successful builds are:
--> DanderSpritz-box: 'virtualbox' provider box: windows_10_danderspritz.box

After that vagrant up also runs into error:

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

~/DanderSpritz_lab$ virtualbox --help
Oracle VM VirtualBox Manager 5.2.12
(C) 2005-2018 Oracle Corporation
All rights reserved.

$ packer --version
0.10.2

$ uname -rva
Linux Test 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

$ vagrant --version
Vagrant 1.9.1

**Comment by francisck** [comment]
To be honest - I have tried to build this directly on just a Debian. I'll give it a try tomorrow and report back. I'm wondering if Packer doesn't like something about how virtual box is installed on that machine.

Can you try running a vagrant box from the internet (in a separate folder, not the danderspritz_lab repo)

```
vagrant init hashicorp/precise64
vagrant up
```

**Comment by david-freistrom** [comment]
Hi,

sorry for my late response. Running a vagrant box in general is also not possible and runs into the same error

It looks like an incompatiblitity of Virtualbox and Vagrant.

Best regards

David

**Comment by francisck** [comment]
Gotcha @dspautz sorry for the pain - but this doesn't seem to be an issue with DanderSpritz lab so I'll be closing the issue.
